### ISSUE TITLE
Repeater's message buffers not being recycled

### ISSUE THREAD

**Issue by keeofkoo** [pipelined/audio#19]
It seems like the repeater's message buffer will never be recycled by the pool allocator (correct me if I'm wrong).

The buffers are "allocated" and wrapped in a `message` struct per source in:

https://github.com/pipelined/audio/blob/8454b94463f3a767ce837cdbf7d2ab9299824888/repeat.go#L40-L46

and they are not getting recycled after being used in:

https://github.com/pipelined/audio/blob/8454b94463f3a767ce837cdbf7d2ab9299824888/repeat.go#L77-L84

**Comment by dudk** [comment]
Hello @keeofkoo. I think you are absolutely correct. Source channel should transfer a pointer to `message` struct and not value.
